apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{class_name}"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "{iops}"
  throughput: "{throughput}"
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer