BOX_IMAGE = "generic/arch"
BOX_VERSION = "4.2.6"
NODE_COUNT = 0

Vagrant.configure("2") do |config|
  config.vm.define "control-plane", primary: true do |cp|
    cp.vm.box = BOX_IMAGE
    cp.vm.box_version = BOX_VERSION
    cp.vm.network "private_network", type: "dhcp"
    cp.vm.hostname = "cp"
  end
  (1..NODE_COUNT).each do |i|
      config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.box_version = BOX_VERSION
        subconfig.vm.network "private_network", type: "dhcp"
        subconfig.vm.hostname = "node#{i}"
      end
  end

  config.vm.provision "shell", path: "install.sh", args: ["1.6.14", "1.1.4", "1.1.1", "1.25.0", "0.4.0"]
end