BOX_IMAGE = "generic/arch"
BOX_VERSION = "4.2.6"
NODE_COUNT = (ENV['NODES'] || "1").to_i

Vagrant.configure("2") do |config|
  config.vm.define "control-plane", primary: true do |cp|
    cp.vm.box = BOX_IMAGE
    cp.vm.box_version = BOX_VERSION
    cp.vm.network "private_network", type: "dhcp"
    cp.vm.hostname = "cp"
    cp.vm.provision "shell", path: "master.sh"
  end
  (1..NODE_COUNT).each do |i|
      config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.box_version = BOX_VERSION
        subconfig.vm.network "private_network", type: "dhcp"
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.provision "shell", path: "node.sh"
      end
  end
  config.vm.synced_folder "configs", "/vagrant/configs", create: true
  config.vm.provision "file", source: "containerd/config.toml", destination: "/tmp/containerd/config.toml"
  config.vm.provision "shell", path: "common.sh", args: ["1.6.14", "1.1.4", "1.1.1", "1.25.0", "0.4.0"]
end