apiVersion: v1
kind: Pod
metadata:
  name: pod-health-check
  labels:
    app.kubernetes.io/name: pod-health-check
spec:
  restartPolicy: Always
  containers:
    - name: sample-app
      image: sample-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 3
        successThreshold: 1
        periodSeconds: 5
        failureThreshold: 2