apiVersion: v1
kind: Service
metadata:
  name: pod-health-check-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pod-health-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000