apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: ebs-persistent-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: ebs-volume-claim
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
          env:
            - name: POSTGRES_PASSWORD
              value: test
          startupProbe:
            exec:
              command:
                - cat
                - /var/lib/postgresql/data/postmaster.pid
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 10
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    name: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
