apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        app.kubernetes.io/name: sample-app
    spec:
      restartPolicy: Always
      containers:
        - name: sample-app
          image: sample-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000