apiVersion: v1
kind: Service
metadata:
  name: simple-deployment-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000