apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      name: demo-nginx
  template:
    metadata:
      labels:
        name: demo-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.0-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: demo-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: nginx-target-group-binding
spec:
  serviceRef:
    name: nginx-service
    port: 8080
  targetType: instance
  targetGroupARN: "$TARGET_GROUP_ARN"