apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      name: rolling-sample-app
  template:
    metadata:
      labels:
        name: rolling-sample-app
    spec:
      restartPolicy: Always
      containers:
        - name: sample-app
          image: sample-app:{tag}
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-service
spec:
  type: NodePort
  selector:
    name: rolling-sample-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000