apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-probe-deployment
spec:
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: test
          startupProbe:
            exec:
              command:
                - cat
                - /var/lib/postgresql/data/postmaster.pid
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 10
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: startup-probe-service
spec:
  selector:
    name: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP