apiVersion: v1
kind: Service
metadata:
  name: first-deployment-service
  namespace: first-namespace
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
