apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app.kubernetes.io/name: simple-pod
spec:
  restartPolicy: Always
  containers:
    - name: sample-app
      image: sample-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000