version: 0.0
os: linux
files:
  - source: configs/named.conf
    destination: /etc
  - source: configs/zones
    destination: /var/named
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/restart-named.sh
      timeout: 180