apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-petclinic-periodic-build
spec:
  schedule: "0/10 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: build
              imagePullPolicy: Never
              image: maven-env:{tag}
              command:
                - /bin/sh
                - -c
              args:
                - git clone https://github.com/spring-projects/spring-petclinic.git && cd spring-petclinic && mvn -T 4 verify