apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      restartPolicy: Always
      volumes:
        - name: secret-volume
          secret:
            secretName: postgres-credentials
      containers:
        - name: demo
          image: alpine:3.17.1
          command: ["/bin/sh", "-c", "--"]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/demo"